module.exports=function(grunt){
    grunt.initConfig({
        watch:{
            jade:{
               files:['views/**'],
                options:{
                    livereload:true//wenjiangaidongchongxinqidongfuwu
                }
            },
            js:{
                files:['public/js/**','models/**/*.js','schemas/**/*.js'],
                //tasks:[jshint],//yufajiancha
                options:{
                    livereload:true
                }
            }
        },
        nodemon:{
            dev:{
                script:"./bin/www",//rukouwenjian
                options:{
                    args:[],
                    ignoredFiles:["README.md","node_modules/**",".DS_Store"],
                    watchedExtensions:["js"],
                    watchedFolders:["./"],
                    debug:true,
                    delayTime:1,
                    env:{
                        PORT:8067
                    }
                },
                cwd:__dirname
            }
        },
        concurrent:{
            tasks:["nodemon","watch"],
            options:{
                logConcurrentOutput:true
            }
        }
    });

    grunt.option("force",true);
    grunt.loadNpmTasks("grunt-contrib-watch");
    grunt.loadNpmTasks("grunt-nodemon");
    grunt.loadNpmTasks("grunt-concurrent");

    grunt.registerTask("default",["concurrent"]);
}